# This file contains default settings for the Vagrant development environment.
#
# If you need to override any of these configurations on your own platform then
# copy this file into a "config.yml" in the vagrant directory
# (directory of this file) and your overrides will take effect on the next
# vagrant up or reload.
#
hostname: "kubernetes-minikube"
box_name: "bento/ubuntu-20.04"
user: "vagrant"
# The minimal number of cpus is 2 for minikube
cpus: 2
memory_size: 4096
copy_vimrc: false
copy_profile: false
copy_bash_aliases: false
copy_bashrc: false
time_zone: "America/New_York"
log_output: "/var/log/bootstrap.log"
# After Version 1.20 deprecated docker. Zimagi depends on docker engine.
kubernetes_version: v1.20.0
